# Required to run your project under the correct environment.
language: php

#Use Mysql service for DB to run testcases
services:
  - mysql

# Versions of PHP you want your project run with.
php:
  - 7.1
  - 7.2

# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan testing-setup --username=root

# Commands you want to run that will verify your build.
script: phpunit

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  allow_failures:
    - php: 5.5
  fast_finish: true

# Customize when the notification emails are sent.
notifications:
    on_success: always
    on_failure: always
    slack: faveohelpdesk:MxVioJBPLDmxiddgzp8PXBqv
